name: neon_x
description: "A Flutter package for neomorphic design - includes custom widgets, icons, text styling, and a timeline widget."
version: 0.0.1
homepage: https://github.com/ShivangSrivastava/neon_x

repository:
  type: git
  url: https://github.com/ShivangSrivastava/neon_x.git

environment:
  sdk: ">=3.2.3 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.9
  google_fonts: ^6.1.0
  velocity_x: ^4.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
